#!/usr/bin/env python3
"""Bake Roboto-Medium.ttf into C headers used by mod_menu CPU blit.

Atlas layout: single-row strip of 8-bit alpha glyphs.
Emits one .h per requested size with:
  - line_height
  - baseline (ascent in px)
  - atlas_w, atlas_h
  - atlas[]  (uint8_t alpha, row-major)
  - glyphs[] for ASCII 32..126
"""

import os
import sys
import freetype

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
FONT_PATH = os.path.join(REPO, "fonts", "Roboto-Medium.ttf")
OUT_DIR = os.path.join(os.path.dirname(__file__), "..")

FIRST_CHAR = 32
LAST_CHAR = 126
GLYPH_COUNT = LAST_CHAR - FIRST_CHAR + 1


def bake(size_px: int, out_name: str, sym_prefix: str):
    face = freetype.Face(FONT_PATH)
    face.set_pixel_sizes(0, size_px)

    ascent = face.size.ascender >> 6
    descent = -(face.size.descender >> 6)
    line_height = ascent + descent

    glyph_data = []
    atlas_w = 0
    atlas_h = line_height + 4

    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        face.load_char(chr(code), freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL)
        bmp = face.glyph.bitmap
        gw = bmp.width
        gh = bmp.rows
        bx = face.glyph.bitmap_left
        by = face.glyph.bitmap_top
        adv = face.glyph.advance.x >> 6

        buf = bytes(bmp.buffer) if (gw > 0 and gh > 0) else b""
        glyph_data.append((code, gw, gh, bx, by, adv, atlas_w, buf))
        atlas_w += gw + 1

    if atlas_w < 1:
        atlas_w = 1

    atlas = bytearray(atlas_w * atlas_h)
    for (_, gw, gh, _, _, _, ox, buf) in glyph_data:
        if gw == 0 or gh == 0:
            continue
        for row in range(gh):
            dst = row * atlas_w + ox
            src = row * gw
            atlas[dst:dst + gw] = buf[src:src + gw]

    out_path = os.path.join(OUT_DIR, out_name)
    with open(out_path, "w") as f:
        f.write("/* Auto-generated by tools/bake_font.py. Do not edit. */\n")
        f.write("#ifndef MOD_MENU_%s_H\n#define MOD_MENU_%s_H\n\n" %
                (sym_prefix.upper(), sym_prefix.upper()))
        f.write("#include <stdint.h>\n\n")
        f.write("#include \"menu_font.h\"\n\n")
        f.write("#define %s_FIRST_CHAR %d\n" % (sym_prefix.upper(), FIRST_CHAR))
        f.write("#define %s_LAST_CHAR  %d\n" % (sym_prefix.upper(), LAST_CHAR))
        f.write("#define %s_LINE_HEIGHT %d\n" % (sym_prefix.upper(), line_height))
        f.write("#define %s_BASELINE   %d\n" % (sym_prefix.upper(), ascent))
        f.write("#define %s_ATLAS_W    %d\n" % (sym_prefix.upper(), atlas_w))
        f.write("#define %s_ATLAS_H    %d\n\n" % (sym_prefix.upper(), atlas_h))

        f.write("static const menu_glyph_t %s_glyphs[%d] = {\n" %
                (sym_prefix, GLYPH_COUNT))
        for (code, gw, gh, bx, by, adv, ox, _) in glyph_data:
            ch = chr(code) if 32 <= code < 127 else "?"
            ch_disp = ch if ch not in ("\\", "\"") else ("\\" + ch)
            f.write("    { %4d, %3d, %3d, %4d, %4d, %3d }, /* '%s' */\n" %
                    (ox, gw, gh, bx, by, adv, ch_disp))
        f.write("};\n\n")

        f.write("static const uint8_t %s_atlas[%d] = {\n" %
                (sym_prefix, len(atlas)))
        for i in range(0, len(atlas), 32):
            row = atlas[i:i + 32]
            f.write("    " + ",".join("%3d" % b for b in row) + ",\n")
        f.write("};\n\n")

        f.write("static const menu_font_t %s_font = {\n" % sym_prefix)
        f.write("    .first_char  = %d,\n" % FIRST_CHAR)
        f.write("    .last_char   = %d,\n" % LAST_CHAR)
        f.write("    .line_height = %d,\n" % line_height)
        f.write("    .baseline    = %d,\n" % ascent)
        f.write("    .atlas_w     = %d,\n" % atlas_w)
        f.write("    .atlas_h     = %d,\n" % atlas_h)
        f.write("    .glyphs      = %s_glyphs,\n" % sym_prefix)
        f.write("    .atlas       = %s_atlas,\n" % sym_prefix)
        f.write("};\n\n")
        f.write("#endif\n")

    print("wrote %s (atlas %dx%d, %d glyphs)" %
          (out_path, atlas_w, atlas_h, GLYPH_COUNT))


def main():
    bake(20, "menu_font_20.h", "menu_font_20")
    bake(28, "menu_font_28.h", "menu_font_28")
    bake(30, "menu_font_30.h", "menu_font_30")
    bake(42, "menu_font_42.h", "menu_font_42")


if __name__ == "__main__":
    main()
