#ifndef CONFIG_H
#define CONFIG_H

#include "config/features.h"
#include "config/identity.h"
#include "config/paths.h"
#include "config/patches.h"
#include "config/runtime_scan.h"
#include "config/camera.h"
#include "config/network.h"

/* Compatibility aliases for the old flat CFG_* namespace. New code should
 * prefer the grouped TAIKO_* names above. */
#define CFG_DONGLE_INDEX   TAIKO_IDENTITY_DONGLE_INDEX
#define CFG_VU_INDEX       TAIKO_IDENTITY_VU_INDEX
#define CFG_DONGLE_SERIAL  TAIKO_IDENTITY_DONGLE_SERIAL
#define CFG_DONGLE_SERIAL_PATH TAIKO_IDENTITY_DONGLE_SERIAL_PATH

#define CFG_CERTS_DIR      TAIKO_PATH_CERTS_DIR
#define CFG_DATA00000_REDIRECT_NAME TAIKO_PATH_DATA00000_REDIRECT_NAME

#define CFG_ENABLE_PROBE_PATCHES        TAIKO_PATCH_PROBE_PATCHES
#define CFG_ENABLE_HARD_DONGLE_PROBE    TAIKO_PATCH_HARD_DONGLE_PROBE
#define CFG_ENABLE_AUTH_STAT_BYPASS     TAIKO_PATCH_AUTH_STAT_BYPASS
#define CFG_ENABLE_FCNTL_DISPATCH       TAIKO_PATCH_FCNTL_DISPATCH
#define CFG_ENABLE_USIO_ENDPOINT_FILTER TAIKO_PATCH_USIO_ENDPOINT_FILTER
#define CFG_ENABLE_PS3A_USJ_EXACT_PID   TAIKO_PATCH_PS3A_USJ_EXACT_PID
#define CFG_ENABLE_XMB_EXIT_PATCH       TAIKO_PATCH_XMB_EXIT
#define CFG_ENABLE_WATCHDOG_PATCHES     TAIKO_PATCH_WATCHDOGS
#define CFG_ENABLE_NET_CLEANUP_GUARD    TAIKO_PATCH_NET_CLEANUP_GUARD
#define CFG_ENABLE_CLEARLOCKS_STUB      TAIKO_PATCH_CLEARLOCKS_STUB

#define CFG_ENABLE_CERT_REPLACEMENT     TAIKO_FEATURE_CERT_REPLACEMENT
#define CFG_ENABLE_HTTP_HOOKS           TAIKO_FEATURE_HTTP_HOOKS
#define CFG_ENABLE_ONLINE_DIAG          TAIKO_FEATURE_ONLINE_DIAG
#define CFG_ENABLE_DATA00000_REDIRECT   TAIKO_FEATURE_DATA00000_REDIRECT
#define CFG_ENABLE_CAMERA_DIAG_HOOKS    TAIKO_FEATURE_CAMERA_DIAG_HOOKS
#define CFG_ENABLE_QR_CARD_READER       TAIKO_FEATURE_QR_CARD_READER
#define CFG_ENABLE_BPREADER_HOOK        TAIKO_FEATURE_BPREADER_HOOK

#define CFG_CAMERA_DIAG_FORCE_GAME_CAMERA TAIKO_CAMERA_DIAG_FORCE_GAME_CAMERA
#define CFG_CAMERA_DIAG_HIDE_GAME_CAMERA  TAIKO_CAMERA_DIAG_HIDE_GAME_CAMERA
#define CFG_CAMERA_DIAG_VERBOSE_PROBE     TAIKO_CAMERA_DIAG_VERBOSE_PROBE
#define CFG_QR_SELFTEST                   TAIKO_CAMERA_QR_SELFTEST
#define CFG_QR_SELF_OPEN_CAMERA           TAIKO_CAMERA_QR_SELF_OPEN_CAMERA

#define CFG_HTTP_WIRE_LOG               TAIKO_NETWORK_HTTP_WIRE_LOG
#define CFG_TLS_SELFTEST                TAIKO_NETWORK_TLS_SELFTEST
#define CFG_FORCE_NETWORK_INDICATOR_ONLINE \
    TAIKO_NETWORK_FORCE_NETWORK_INDICATOR_ONLINE
#define CFG_FORCE_ONLINE_CHECK_READY       TAIKO_NETWORK_FORCE_ONLINE_CHECK_READY
#define CFG_FORCE_GAME_NET_SERVICE_CONTEXT \
    TAIKO_NETWORK_FORCE_GAME_NET_SERVICE_CONTEXT

#define CFG_RUNTIME_SCAN_USB_PATCHES       TAIKO_SCAN_USB_PATCHES
#define CFG_RUNTIME_SCAN_HTTP_HOOKS        TAIKO_SCAN_HTTP_HOOKS
#define CFG_RUNTIME_SCAN_XMB_EXIT_PATCH    TAIKO_SCAN_XMB_EXIT_PATCH
#define CFG_RUNTIME_SCAN_WATCHDOG_PATCHES  TAIKO_SCAN_WATCHDOG_PATCHES
#define CFG_RUNTIME_SCAN_CAMERA_HOOKS      TAIKO_SCAN_CAMERA_HOOKS
#define CFG_RUNTIME_SCAN_USB_HOOKS         TAIKO_SCAN_USB_HOOKS
#define CFG_SCAN_TEXT_START                TAIKO_SCAN_TEXT_START
#define CFG_SCAN_TEXT_END                  TAIKO_SCAN_TEXT_END

#endif
