#ifndef TAIKO_CONFIG_CAMERA_H
#define TAIKO_CONFIG_CAMERA_H

#define TAIKO_CAMERA_DIAG_FORCE_GAME_CAMERA 0
#define TAIKO_CAMERA_DIAG_HIDE_GAME_CAMERA  1
#define TAIKO_CAMERA_DIAG_VERBOSE_PROBE     0

#define TAIKO_CAMERA_QR_SELFTEST            0
#define TAIKO_CAMERA_QR_SELF_OPEN_CAMERA    1

#endif
