#ifndef TAIKO_CONFIG_FEATURES_H
#define TAIKO_CONFIG_FEATURES_H

#define TAIKO_FEATURE_CERT_REPLACEMENT     0
#define TAIKO_FEATURE_HTTP_HOOKS           1
#define TAIKO_FEATURE_ONLINE_DIAG          0
#define TAIKO_FEATURE_DATA00000_REDIRECT   1
#define TAIKO_FEATURE_CAMERA_DIAG_HOOKS    1
#define TAIKO_FEATURE_QR_CARD_READER       1
#define TAIKO_FEATURE_BPREADER_HOOK        1

#endif
