#ifndef TAIKO_CONFIG_IDENTITY_H
#define TAIKO_CONFIG_IDENTITY_H

#define TAIKO_IDENTITY_DONGLE_INDEX   0
#define TAIKO_IDENTITY_VU_INDEX       0
#define TAIKO_IDENTITY_DONGLE_SERIAL  "268410000000"
#define TAIKO_IDENTITY_DONGLE_SERIAL_PATH \
    "/dev_hdd0/game/SCEEXE001/USRDIR/dongle_serial.txt"

#endif
