#ifndef TAIKO_CONFIG_IDENTITY_H
#define TAIKO_CONFIG_IDENTITY_H

#define TAIKO_IDENTITY_DONGLE_INDEX   0
#define TAIKO_IDENTITY_VU_INDEX       0
#define TAIKO_IDENTITY_DONGLE_SERIAL  "268410000000"

#endif
