#ifndef TAIKO_CONFIG_PATCHES_H
#define TAIKO_CONFIG_PATCHES_H

#define TAIKO_PATCH_PROBE_PATCHES        1
#define TAIKO_PATCH_HARD_DONGLE_PROBE    1
#define TAIKO_PATCH_AUTH_STAT_BYPASS     1
#define TAIKO_PATCH_FCNTL_DISPATCH       1
#define TAIKO_PATCH_USIO_ENDPOINT_FILTER 1
#define TAIKO_PATCH_PS3A_USJ_EXACT_PID   1
#define TAIKO_PATCH_XMB_EXIT             1
#define TAIKO_PATCH_WATCHDOGS            1
#define TAIKO_PATCH_NET_CLEANUP_GUARD    1
#define TAIKO_PATCH_CLEARLOCKS_STUB      1
#define TAIKO_PATCH_ALLOW_SCREEN_TEARING 0
#define TAIKO_PATCH_DANI_DOJO_UNLOCK     1

#endif
